// alert("This is my javascript class 1")
// alert("this is js")
// alert("hello")
// document.write("<h4>javascript is easy isn't it? </h4>")
// console.log("javascript print in console")
var userName = prompt("enter your name of your fav subject")
var userName2 = prompt("enter your name of your fav subject 2")
var userName3 = prompt("enter your name of your fav subject 3")
var userName4 = prompt("enter your name of your fav subject 4")
var userName5 = prompt("enter your name of your fav subject 5")
document.write('<h1>' + userName + '</h1>')
document.write('<h1>' + userName2 + '</h1>')
document.write('<h1>' + userName3 + '</h1>')
document.write('<h1>' + userName4 + '</h1>')
document.write('<h1>' + userName5+ '</h1>')